### ISSUE TITLE
Map editor

### ISSUE THREAD

**Issue by kosuda-kun** [hodasemi/GameES#11]
Hey 
Ich fände es sinnvoll wenn du eine Meldung einfügen könntest die mich fragt ob ich ohne speichern den map Editor verlassen will (ich weiß sowas nervt zwar aber mir ist es eben passiert das ich etwas erstellt hab und dann ausersehen ins Hauptmenü gegangen bin und alles futsch)

Hoffe das klappt weiter so gut 
Kosuda

**Comment by hodasemi** [comment]
solved
